-- 코드를 작성해주세요
-- 수원지역, 연도별 평균 미세먼지 오염도(PM10), 평균 초미세먼지 오염도(PM2.5), 소수 셋째 반올림
SELECT YEAR(YM) AS YEAR, ROUND(AVG(PM_VAL1),2) AS 'PM10', ROUND(AVG(PM_VAL2),2) AS 'PM2.5'
FROM AIR_POLLUTION
WHERE LOCATION2 LIKE '수원'
GROUP BY YEAR(YM)
ORDER BY YEAR(YM);