-- 코드를 입력하세요
# WITH TBL AS(SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
#       FROM REST_INFO
#       GROUP BY FOOD_TYPE
# )
# SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, B.FAVORITES
# FROM REST_INFO AS A INNER JOIN TBL as B
# ON A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = B.FAVORITES
# ORDER BY 1 DESC;

WITH TBL AS(SELECT *, RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS NUM
FROM REST_INFO)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM TBL
WHERE NUM = 1
ORDER BY 1 DESC;