-- 코드를 입력하세요
WITH J2021 AS (SELECT *
FROM USER_INFO
WHERE YEAR(JOINED) = "2021")

,P2021 AS(
SELECT COUNT(DISTINCT(S.USER_ID)) AS PURCHASED_USERS, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
FROM ONLINE_SALE AS S JOIN J2021 AS U ON S.USER_ID = U.USER_ID
GROUP BY YEAR, MONTH)

SELECT YEAR, MONTH, PURCHASED_USERS, ROUND(PURCHASED_USERS/(SELECT COUNT(*) FROM J2021),1)AS PUCHASED_RATIO
FROM P2021
ORDER BY 1, 2;