-- 코드를 입력하세요
# WITH J2021 AS (SELECT *
# FROM USER_INFO
# WHERE YEAR(JOINED) = "2021")
# # SELECT * FROM J2021;
# ,P2021 AS(
# SELECT DISTINCT(S.USER_ID), YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
# FROM ONLINE_SALE AS S LEFT JOIN J2021 AS U ON S.USER_ID = U.USER_ID
# WHERE U.USER_ID IS NOT NULL),
# CNT AS (SELECT COUNT(*) AS CNT FROM J2021)
# SELECT YEAR, MONTH, ROUND(COUNT(USER_ID)/C.CNT,1)
# FROM P2021 CROSS JOIN CNT AS C
# GROUP BY YEAR, MONTH
# ORDER BY 1, 2;


WITH TOTAL_USER AS (SELECT * FROM USER_INFO WHERE YEAR(JOINED) = 2021)

SELECT YEAR(S.SALES_DATE) YEAR, MONTH(S.SALES_DATE) MONTH, COUNT(DISTINCT U.USER_ID) PURCHASED_USERS, ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(*) FROM TOTAL_USER), 1) PUCHASED_RATIO
FROM USER_INFO U
JOIN ONLINE_SALE S
ON U.USER_ID = S.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY 1, 2
ORDER BY 1, 2