-- 코드를 작성해주세요
WITH RECURSIVE GEN AS(SELECT ID, PARENT_ID, 1 AS G 
                 FROM ECOLI_DATA
                 WHERE PARENT_ID IS NULL
                 UNION ALL
                 SELECT D.ID, D.PARENT_ID, E.G+1 AS G
                 FROM ECOLI_DATA AS D JOIN GEN AS E ON D.PARENT_ID = E.ID)

SELECT COUNT(ID) AS COUNT, G AS GENERATION
FROM GEN
WHERE ID NOT IN(
SELECT PARENT_ID
FROM GEN
WHERE PARENT_ID IS NOT NULL)
GROUP BY G
