-- 코드를 입력하세요


WITH TRUCK AS(
SELECT H.*, 
       C.DAILY_FEE,
       DATEDIFF(END_DATE, START_DATE) + 1 DURATION,
       CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE '해당 없음' END  duration_type
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID AND C.CAR_TYPE = '트럭'    # CAR TABLE '트럭' 필터링
), TRUCK2 AS(
SELECT 
    HISTORY_ID,
    CASE WHEN T.DURATION_TYPE = '해당 없음' THEN DAILY_FEE * DURATION 
         WHEN T.DURATION_TYPE IN ('7일 이상','30일 이상','90일 이상') THEN DAILY_FEE * DURATION * (1-discount_rate/100)
         ELSE 0 END FEE
FROM TRUCK T LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON T.DURATION_TYPE = P.DURATION_TYPE AND P.CAR_TYPE = '트럭'  # PLAN TABLE '트럭' 필터링
ORDER BY 2 DESC, 1 DESC)

SELECT HISTORY_ID, ROUND(FEE) AS FEE
FROM TRUCK2