-- 코드를 작성해주세요
WITH FRONT AS (SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE CATEGORY = 'Front End')

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS AS D
WHERE D.SKILL_CODE & (SELECT CODE FROM FRONT)
ORDER BY 1;