-- 코드를 작성해주세요
WITH TMP AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX
FROM ECOLI_DATA
GROUP BY YEAR
)


SELECT YEAR(ED1.DIFFERENTIATION_DATE) AS YEAR, (T.MAX - ED1.SIZE_OF_COLONY) AS YEAR_DEV, ED1.ID
FROM ECOLI_DATA AS ED1 LEFT JOIN TMP AS T ON YEAR(DIFFERENTIATION_DATE) = T.YEAR
ORDER BY 1, 2;