-- 코드를 입력하세요
# SELECT BOARD_ID, WRITER_ID,	TITLE, PRICE, 
# CASE 
#     WHEN  STATUS = 'SALE' THEN '판매중'
#     WHEN  STATUS = 'RESERVED' THEN '예약중'
#     ELSE '거래완료'
#     END AS STATUS
# from USED_GOODS_BOARD
# where CREATED_DATE = '2022-10-05'
# order by BOARD_ID DESC;


SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, 
CASE WHEN STATUS LIKE 'DONE' THEN '거래완료'
    WHEN STATUS LIKE 'SALE' THEN '판매중'
    ELSE  '예약중' END AS STATUS
FROM USED_GOODS_BOARD
where CREATED_DATE = '2022-10-05'
ORDER BY BOARD_ID DESC;