# WITH TBL AS (SELECT I.ID, N.FISH_NAME, I.LENGTH, RANK() OVER(PARTITION BY I.FISH_TYPE ORDER BY LENGTH DESC) AS NUM
# FROM FISH_INFO AS I LEFT JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
# )
# SELECT ID, FISH_NAME, LENGTH
# FROM TBL
# WHERE NUM = 1
# ORDER BY 1;




WITH TMP AS (SELECT ID, FISH_TYPE, LENGTH
FROM(
SELECT *, RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS NUM
FROM FISH_INFO) AS T
WHERE NUM = 1)

SELECT ID, FISH_NAME, LENGTH
FROM TMP LEFT JOIN FISH_NAME_INFO AS F ON TMP.FISH_TYPE = F.FISH_TYPE
ORDER BY 1;















