-- 코드를 입력하세요
WITH TBL AS(
    SELECT * FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1
)
, TBL2 as (select * from used_goods_board)

SELECT CONCAT('/home/grep/src/',BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID IN (SELECT BOARD_ID FROM TBL)
ORDER BY FILE_ID DESC;