-- 코드를 입력하세요
WITH TBL AS (SELECT PRODUCT_ID, CATEGORY, MAX(PRICE) AS PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ( "과자", "국", "김치", "식용유")
GROUP BY CATEGORY)

SELECT C.CATEGORY, C.PRICE AS MAX_PRICE, C.PRODUCT_NAME
FROM FOOD_PRODUCT AS C LEFT JOIN TBL AS T ON C.PRICE = T.PRICE AND C.CATEGORY = T.CATEGORY
WHERE T.PRICE IS NOT NULL
ORDER BY 2 DESC;